### ISSUE TITLE
Export animated objects from Unity as Glb file got an error when imported into ThreeJS  via GLTFLoader

### ISSUE THREAD

**Issue by justinduynguyen** [needle-tools/needle-engine-support#100]
How to reproduce this issue?
1. Animate object using animation editor of unity engine.
2. Add Animation component and assign animclip.
3. Add Gltf Object component into it.
4. Click Selected objects as glb.
5.  Import exported glb file into Threejs project and load the file with GLTFLoader via load function.

![Screenshot 2022-10-25 143440](https://user-images.githubusercontent.com/18099515/197713107-a3f8a3c1-25e9-463c-967d-ed7b28d94c0b.png)

**Comment by marwie** [comment]
If you just want to animate something and load it somewhere else without any Needle Engine features you can also use UnityGLTF directly (there's also a context menu item to export a gltf/glb)

**Comment by Podden** [comment]
I'd this error when I'm exporting an animation clip with "Default Value" in them. This Default stuff happens when I'm removing all keyframes from subvalues. Putting just one keyframe in there, everything is exporting fine. Maybe that's the case here as well?
![grafik](https://user-images.githubusercontent.com/3932988/226971683-c2f42487-ae3d-4211-9baa-6ba8b334915e.png)
