### ISSUE TITLE
Spatial Triggers do not work when the MeshRenderer is disabled on the gameobject they are on

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#60]
Using Unity 2022.1.16f1, Exporter 2.23.0-pre

I have sent a repro scene across, this project was upgraded from 2020.3.38f1

Repro this by going Scenes>Test and try running with SceneRoot > Content > Turn on/off the MeshRenderers on the Zone 0-3 gameobjects to see this

**Comment by marwie** [comment]
Thanks for the report. This is an architectural issue right now where enabling/disabling renderers implictly sets the ``active`` state of the object they are assigned to (because they set ``visibility`` and ``visibility`` controls if components will be enabled or disabled). 

This is planned to be fixed in a future version

**Comment by ROBYER1** [comment]
What would you suggest as a workaround, I assume just don't have a meshrenderer on the object using the Spatial Trigger
